# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_BEAU) += hcall.o
obj-$(CONFIG_BEAU_VIRTIOBLK_BACKEND) += virtio-blk-backend.o
obj-$(CONFIG_BEAU_VIRTIOFS_BACKEND) += virtio-fs-backend.o
obj-$(CONFIG_BEAU_VIRTIORNG_BACKEND) += virtio-rng-backend.o
obj-$(CONFIG_BEAU_VWDT) += vwdt.o
