# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_BEAU) += hcall.o virtio-proxy-backend.o
obj-$(CONFIG_BEAU_PM) += beau-pm.o
obj-$(CONFIG_BEAU_VIRTIOBLK_BACKEND) += virtio-blk-backend.o
obj-$(CONFIG_BEAU_VIRTIOFS_BACKEND) += virtio-fs-backend.o
obj-$(CONFIG_BEAU_VIRTIORNG_BACKEND) += virtio-rng-backend.o
obj-$(CONFIG_BEAU_VIRTIOI2C_BACKEND) += virtio-i2c-backend.o
obj-$(CONFIG_BEAU_VIRTIONET_BACKEND) += virtio-net-backend.o
obj-$(CONFIG_BEAU_VWDT) += vwdt.o
obj-$(CONFIG_BEAU_EDU_TEST) += edu-test.o
obj-$(CONFIG_BEAU_IPC_TEST) += ipc-test.o
